# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Location Services' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Location Services
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GoogleMaps'

end
